### ISSUE TITLE
[v2.0] Handle missing gatenlp package

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-python#18]
At least: have a nice error message. 
Maybe better: if not installed, warning, on the fly export of own version from jar?

**Comment by greenwoodma** [comment]
as far as I know (and I'm no python expert) the python code can actually be loaded from within the jar as long as it's on the python classpath. See https://docs.python.org/3.6/library/zipimport.html

(ignore me if I've got the wrong end of the stick, but I was intending to look at this myself, but then you started on a new version of the plugin so I didn't get any further)

**Comment by johann-petrak** [comment]
Thanks!
I did not know about this option but I think exporting the lib and setting the path in the environment variable would have the advantage that the same python source code would work, no matter if the lib is installed through pip or prepared by the plugin. 
Either way, for that the python lib should probably get added as a submodule, as it is done in the LearningFramework.

**Comment by greenwoodma** [comment]
No. We need to explicitly prohibit loading the python code from anywhere other than from within the plugin. The whole point of plugins is that they are self contained and that when you use a specific version of a plugin we can guarantee exactly which code is being run. This is the minimum requirement for any reproducability claims.

So we must guarantee that the python code that is part of the plugin (i.e. not the custom code the plugin is running) is in fact the only version of the code available to the python runtime.

To me the simplest way of doing that is to ensure the jar file is on the python path (I assume at the beginning to ensure it's searched first) and to then load the code from within it. This also avoids all the nasty problems associated with trying to automatically extract resources from within the jar in normal usage (especially important in embedded situations where there may be issues with write access etc.)

**Comment by johann-petrak** [comment]
Good points, you are right. Let's directly import from the JAR.

**Comment by johann-petrak** [comment]
It is not easily possible to make it completely self-contained though, since we always need to rely on some python installation and properly installed dependencies. 
The pythonic way would probably be to have an environment set up with the correct versions of python and all required packages and let the plugin use that environment. 
So if there is a need to make sure other things are properly installed and maybe even an environment should be set up, having the python gatenlp package properly installed there is not rocket science either.

**Comment by ianroberts** [comment]
Maybe there’s a case for including the relevant requirements.txt in the plugin and then having a right click action on the python PR that runs a process to create a venv, install those requirements, and configure the `pythonBinaryUrl` parameter to point to the `venv/bin/python`. It’s not perfect as we know but it’d reduce the friction for a first time setup.

**Comment by johann-petrak** [comment]
Hmm I was more thinking about the case Mark mentioned, where this should be run in some kind of embedded scenario. If, as he mentions, there may be issues with write access, there is no way to setup the python env automatically. 
In general, all such automatic setups are a bit brittle given the multiple ways of how one can install python , can have environments (my preferred approach normally is to use a conda env) in python etc. and are rather diametrically opposite to how Python users do things.
If somebody uses python and wants to use Python with GATE, should we expect them to be competent enough to know how to install python, dependencies or set up environments?
Maybe the most important question is how to make it easiest for us to deal with the inevitable support questions we will get ...

**Comment by johann-petrak** [comment]
Anyway, at the moment there are not many dependencies and I think I can get rid of most for now or if they are small, include them in the zip pythonpath. So maybe we can keep it simple in the initial version and think about all that fancy stuff later.

**Comment by johann-petrak** [comment]
Closing this for now, this should now work in principle and copy the python package into the JAR, then use that when running.
