### ISSUE TITLE
Good way to specify which annotation sets to send?

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-Python#20]
If documents are already heavily annotated and the python process does not need all those annotations, it would save a lot of time to not send those annotations in the first place.

So it would be good to have a parameter where the user can specify e.g. the annotation sets to send, where the default would be to send them all, and where it is also possible to not send any set at all. 

Not sure how to specify that in a user-friendly way, given that the default annotation set has an empty name, set names can contain any character in etc.

**Comment by johann-petrak** [comment]
OK, we could just use a string input field which can be used to enter a comma separated list of annotation set names. If the names are odd, quote them. 
If the field is empty, do not send over any annotation set.
By default the field contains the special symbol "*" to indicate that all annotation sets should be sent. 
To parse the input, use:
https://commons.apache.org/proper/commons-lang/javadocs/api-2.4/org/apache/commons/lang/text/StrTokenizer.html

**Comment by drj11** [comment]
I'm skeptical that the performance is worth it. What's the worst case? Can we measure it?

**Comment by johann-petrak** [comment]
It should be possible to measure it :)
I had already corpora of millions of documents where we had many annotation sets with lots of annotations (each of which having lots of features) for each document, so I think it could well be worth it. 
One of the basic ideas of the bdoc design and how it can get converted from and to gate is also that it can be used to represent "partial" documents. I think it would be good to pass around only what is needed when we split up processing using multiprocessing more and more. 

I removed the v2.0 label from this though, so we can look into this after the initial release and attend to more important things before :)

**Comment by greenwoodma** [comment]
I guess for a single document it probably doesn't make a huge amount of difference. Once we start processing huge corpora though I would imagine it will. If you think about a large collection of patent documents for instance, then each document will be huge and just serialising the Token annotations will take both time and space. When you start doing it for a large corpora the inefficiency will kill us. If we can just transfer an annotation set, or even just specific types within a set then that would help.

**Comment by johann-petrak** [comment]
There is a complication here: if we send only some annotation sets over, and send back all the annotation sets that are created on the python side, then it is possible that python creates new annotations in a set which is already on the GATE side. 
Normally, we trust python to assign the correct annotation ids and we use those ids when updating the sets on the GATE side, so that annotations that reference other annotations by id are still correct.
However, if python does not see the annotations from a set it adds to, those ids will be wrong. 

The only correct way to deal with this I can see is that while we do not send the annotations, we still send the highest annotation id of each existing set to python, so that any new annotations in such a set will get unused annotation ids.

**Comment by greenwoodma** [comment]
Why not make life simpler and assume, as GATE actually does, that the IDs are unique across the document. That way you only need to pass the single highest ID for the document across rather than for each set.

**Comment by johann-petrak** [comment]
I had been thinking about making life simpler, but I originally preferred to have ids local to a set. That way sets are completely independent of each other and could even get manipulated in parallel. It just looks cleaner logically to do this per set than have a global id. 
On the other hand, having a global id would not just make this much easier, it would allow to link between annotations of different sets, if needed. 
Ahh well, I guess I probably will  change the gatenlp library to track the ids globally per document.

**Comment by johann-petrak** [comment]
Thinking some more, the problems by copying the specific implementation detail of DocumentImpl are bigger than what we need in here.  Not going to change the handling of annotation ids.

**Comment by johann-petrak** [comment]
We have now method `BdocDocumentBuilder.addSet(name, annset, nextAnnotationId)` for doing this: for all sets not to transmit, add an empty set but with the current next id of the document.

**Comment by johann-petrak** [comment]
Implemented parameter `setsToUse` which is a Set of names. If any name is *, all sets are transferrred (this is the default), otherwise, only the ones specified are transferred in full, but for the rest we transfer the nextAnnotationId.
