### ISSUE TITLE
Pythonpath: add containing directory of specified python file

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-Python#44]
If the python file is on a normal file system, make sure the containing directory is in the pythonpath so a user can import other modules and packages from that directory for larger projects.

**Comment by drj11** [comment]
Yes. I went back and forth before agreeing about this, but I think that you're right. It will be least surprising if it works the same as `python my-script.py`: `my-script.py` can `import mymod.py` where `mymod.py` is in the same directory as `my-script.py`.

**Comment by johann-petrak** [comment]
This works.
