### ISSUE TITLE
tests fail when trying to compile the plugin

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gateplugin-Python#46]
When I try and compile a clean clone of the plugin I get the following errors

```
Running gate.plugin.python.tests.PythonPrTest
Traceback (most recent call last):
  File "/home/mark/gate-top/externals/gateplugin-Python/./src/test/python/tiny1.py", line 3, in <module>
    from gatenlp import interact, GateNlpPr, Document
ModuleNotFoundError: No module named 'gatenlp'
SYSTEM PATH: ['/home/mark/gate-top/externals/gateplugin-Python/src/test/python', '/home/mark/gate-top/externals/gateplugin-Python/target/classes/resources/pythonpath', '/home/mark/miniconda3/lib/python37.zip', '/home/mark/miniconda3/lib/python3.7', '/home/mark/miniconda3/lib/python3.7/lib-dynload', '/home/mark/miniconda3/lib/python3.7/site-packages']
Traceback (most recent call last):
  File "/home/mark/gate-top/externals/gateplugin-Python/./src/test/python/test1.py", line 5, in <module>
    from gatenlp import interact, GateNlpPr, Document
ModuleNotFoundError: No module named 'gatenlp'
SYSTEM PATH: ['/home/mark/gate-top/externals/gateplugin-Python/src/test/python', '/home/mark/gate-top/externals/gateplugin-Python/target/classes/resources/pythonpath', '/home/mark/miniconda3/lib/python37.zip', '/home/mark/miniconda3/lib/python3.7', '/home/mark/miniconda3/lib/python3.7/lib-dynload', '/home/mark/miniconda3/lib/python3.7/site-packages']
Traceback (most recent call last):
  File "/home/mark/gate-top/externals/gateplugin-Python/./src/test/python/test2.py", line 5, in <module>
    from gatenlp import interact, GateNlpPr, Document
ModuleNotFoundError: No module named 'gatenlp'
Python path:
/home/mark/miniconda3/bin/python
PYTHON DEBUG OUTPUT:
PYTHONHOME: None
PYTHON VERSION: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
PYTHON PATH: ['/home/mark/gate-top/externals/gateplugin-Python/src/test/python', '/home/mark/miniconda3/lib/python37.zip', '/home/mark/miniconda3/lib/python3.7', '/home/mark/miniconda3/lib/python3.7/lib-dynload', '/home/mark/miniconda3/lib/python3.7/site-packages']
Traceback (most recent call last):
  File "src/test/python/debug.py", line 7, in <module>
    import sortedcontainers
ModuleNotFoundError: No module named 'sortedcontainers'
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.292 sec <<< FAILURE!
testPythonPr00(gate.plugin.python.tests.PythonPrTest)  Time elapsed: 0.123 sec  <<< ERROR!
gate.util.GateRuntimeException: Cannot run the python program, my have a syntax error
	at gate.plugin.python.PythonPr.whenStarting(PythonPr.java:804)
```

Python not being my strong point I'm not sure what the problem is here, but I'm guessing the code for ensuring the gate python code is available to the python binary isn't working properly?

**Comment by johann-petrak** [comment]
The gatenlp package is included in the plugin repo as a submodule, so maybe that submodule did not get cloned. 
You can ensure this by doing this inside the plugin repo once:
* git submodule init
* git submodule update

Or, initially clone it with the --recurse-submodules parameter

**Comment by greenwoodma** [comment]
that gets rid of the gatenlp package errors but still leaves the errors referring to `sortedcontainers`

**Comment by johann-petrak** [comment]
Yes, sortedcontainers is a requirement, you need to do "pip install sortedcontainers" first, see
http://gatenlp.github.io/gateplugin-Python/python-install.html

**Comment by greenwoodma** [comment]
right, I missed that but..... I thought part of the point was that we'd make use of requirements.txt to get everything needed automatically. I'm probably being stupid but why doesn't that includes `sortedcontainers`?

**Comment by johann-petrak** [comment]
`requirements.txt` and `setup.py` dependency declarations only help for automatically installing the dependencies when doing `pip install gatenlp`.
Here we are just *using* gatenlp from the python script. So no installation is done from the python plugin. We could automatically install, but I am against it because it could mess up a user's python setup and anyone knowing enough python for wanting to use this should have no problem to just install the sortedcontainers themselves. 

I am actually already checking for the sortedcontainerspackage when the gatenlp package is imported (which is also done when syntax checking the code) and I emit my own error message.
I did not want to give any instructions about how to install the sortedcontainers package there though since again it can be done in several ways in Python.

**Comment by greenwoodma** [comment]
fair enough

**Comment by johann-petrak** [comment]
OK I updated gatenlp to give a nicer error message if the dependency is missing and not raise an Exception which shows all that unnecessary traceback info. 

The output should now be:
```
ERROR: required package sortedcontainers cannot imported!
Please install, using e.g. 'pip install -U sortedcontainers'
```

**Comment by greenwoodma** [comment]
you might want to make that "cannot be imported" but that's a much nicer error message, thanks!

**Comment by johann-petrak** [comment]
I should not work on three things at the same time ...

Thanks :)
