### ISSUE TITLE
SourcedString comes from NLTK (Apache license), so it must either be replaced, or project needs apache license.

### ISSUE THREAD

**Issue by domrout** [GateNLP/gateplugin-python#6]

**Comment by greenwoodma** [comment]
as far as I know you can safely include apache licensed code inside a (L)GPL v3 project without any issues; you can't do it the other way around though.

See https://www.apache.org/licenses/GPL-compatibility.html for more details straight from the apache project.

**Comment by johann-petrak** [comment]
2.0-SNAPSHOT does not rely on SourcedString any more.
