### ISSUE TITLE
Does not work with Python 3. Get: ModuleNotFoundError in gate/__init__.py

### ISSUE THREAD

**Issue by sunandabansal** [GateNLP/gateplugin-python#9]
Hi, I am getting this error 

```
Traceback (most recent call last):
  File "/home/sunanda/Documents/path/to/my/folder/tokenizer.py", line 1, in <module>
    import gate, sys
  File "/home/sunanda/GATE_Developer_8.4.1/clac/plugins/gateplugin-python/gate/__init__.py", line 1, in <module>
    from annotation import Annotation
ModuleNotFoundError: No module named 'annotation'
```

when I try to use python 3 binaries. It works fine when I use python 2. Can you please tell me what can I do to fix it.

**Comment by drj11** [comment]
Currently only works with Python 2. We are intending to support Python 3 but have no specific timeline yet.

**Comment by matanster** [comment]
Ouch, python 2 is kind of old now. Do you know of any alternative, other than writing one's one IPC?

**Comment by drj11** [comment]
@matanster I actually ported it to Python 3 a few days ago, I just forgot to update this issue or make a note of that in the `README.md`.

You'll have to checkout the `master` branch to use it, following the README.

If you have problems, raise an issue!

**Comment by matanster** [comment]
Oh this is awesome!

I wonder which concerns does the plugin take upon itself, and which ones does it leave to project-specific implementation. I can see few responsibilities that such a bridge plugin can take: Startup coordination (that gate and the underlying python stuff have both initialized before starting to communicate), IPC, object conversion (GATE Annotation/Document objects to something pythonic or to string data like json). Am I missing anything? are any of the layers particularly opinionated or having well-known by-design limitations?

**Comment by drj11** [comment]
GATE (either GATE Developer, or gate-core) starts the python process. The rest is handled by this package which has a Java part (to convert GATE documents from Java to JSON) and a Python part (to convert JSON to Python documents). The Python package includes a document model similar to GATE.

There is an example in the README that is complete: https://github.com/GateNLP/gateplugin-python#the-python-gate-library

**Comment by matanster** [comment]
Sounds like a good design to me
